services:
  mediawiki:
    image: ghcr.io/georgedewar/carhackingwiki
    restart: always
    ports:
      - 8080:80
    volumes:
      - ./images:/var/www/html/images
      - ./LocalSettings.php:/var/www/html/LocalSettings.php
      - ./public/favicon.ico:/var/www/html/favicon.ico
      - ./public/robots.txt:/var/www/html/robots.txt
    extra_hosts:
      - "host.docker.internal:host-gateway"
