- name: My first play
  hosts: hosts
  tasks:
    - name: Install nginx
      ansible.builtin.apt:
        name: nginx
        state: present

    - name: Install certbot
      community.general.snap:
        name: certbot
        state: present
        classic: true

    - name: Add Docker GPG apt Key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      ansible.builtin.apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu noble stable
        state: present

    - name: Update apt and install docker-ce
      ansible.builtin.apt:
        name: docker-ce
        state: present
        update_cache: true

    - name: Obtain certificates
      ansible.builtin.command:
        cmd: certbot certonly --nginx --keep-until-expiring -d "{{ item }}"
      register: certbot_output
      changed_when: "'Successfully received certificate' in certbot_output.stdout"
      loop:
        - carhackingwiki.com
        - nissanleaf.carhackingwiki.com

    - name: Automatically renew certificates
      ansible.builtin.cron:
        name: "renew certificates"
        minute: "0"
        hour: "0"
        job: 'certbot renew --renew-hook "systemctl reload nginx"'
        state: present

    - name: Install nginx configuration
      ansible.builtin.copy:
        src: ../nginx.conf
        dest: /etc/nginx/sites-available/default
        mode: "0644"
      notify:
        - Restart nginx

  handlers:
    - name: Restart nginx
      ansible.builtin.systemd:
        name: nginx
        state: restarted
